/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const axios: typeof import('axios')['default']
  const request: typeof import('./src/utils/request')['default']
}
